#!/usr/bin/expect

set timeout -1

set ip [lindex $argv 0]
set file3 [lindex $argv 3]
spawn /usr/bin/sftp -o StrictHostKeyChecking=no root@$ip
expect "id_rsa':"
send "siemens\r"
expect "sftp>"
send "lcd logs/\r"
send "get /opt/mgmtservices/statusservice/logs/statusservice.log\r"
sleep 1
expect "sftp>"
send "get /opt/mgmtservices/relay/logs/relay.log\r"
expect "sftp>"
sleep 1
send "get /opt/mgmtservices/probes/logs/probe.log\r"
expect "sftp>"
sleep 1
send "bye\r"
