#!/usr/bin/expect

set timeout -1

set f [open "cmdslist"]
set commands [split [read $f] "\n"]
close $f

set ip [lindex $argv 0]
spawn /usr/bin/ssh  -o StrictHostKeyChecking=no user@$ip
sleep 1
#expect "Password:"
send "hvgdl3p@\r" 
expect ">"
send "enable\r"
expect "Password:"
send "gplrt4@6\r"
send "sh dns lookup iSBCIMSCoreMaaP SRV  _sip._tcp.awsprodccmi.national.uvp.els-an.att.net\r"
sleep 25
expect "#"
send "exit\r"
expect ">"
send "exit\r"
expect eof

