#!/usr/bin/expect

set timeout -1

set user [lindex $argv 1]
set ip [lindex $argv 0]
set Password [lindex $argv 2]
spawn /usr/bin/ssh  -o StrictHostKeyChecking=no user@$ip
sleep 1
#expect "Password:"
send "hvgdl3p@\r" 
expect ">"
send "enable\r"
expect "Password:"
send "gplrt4@6\r"
expect "#"
send "sh health\r"
expect "#"
send "sh ip connections\r"
expect "#"
send "exit\r"
expect ">"
send "exit\r"
expect eof

